using System.CommandLine;

namespace Acjr3.Commands.Core;

public static class RequestCommandBuilder
{
    public static Command Build(IServiceProvider services)
    {
        var command = new Command(
            "request",
            "Execute a Jira REST API request. For example: acjr3 request GET /rest/api/3/myself.");
        var methodArg = new Argument<string?>("method", () => null, "HTTP method: GET|POST|PUT|DELETE|PATCH") { Arity = ArgumentArity.ZeroOrOne };
        var pathArg = new Argument<string?>("path", () => null, "Relative Jira path (for example, /rest/api/3/myself)") { Arity = ArgumentArity.ZeroOrOne };

        var queryOpt = new Option<string[]>("--query", "Query parameter key=value. Repeat for additional values.") { AllowMultipleArgumentsPerToken = true };
        var headerOpt = new Option<string[]>("--header", "Header key=value. Repeat for additional values.") { AllowMultipleArgumentsPerToken = true };
        var acceptOpt = new Option<string>("--accept", () => "application/json", "Accept header value.");
        var contentTypeOpt = new Option<string?>("--content-type", "Content-Type header value.");
        var bodyOpt = new Option<string?>("--body", "Inline JSON request payload (JSON object).");
        var bodyFileOpt = new Option<string?>("--body-file", "Path to JSON request payload file (JSON object).");
        var inOpt = new Option<string?>("--in", "Path to request payload file, or '-' for stdin.");
        var inputFormatOpt = new Option<string>("--input-format", () => "json", "Input format: json|adf|md|text.");
        var outOpt = new Option<string?>("--out", "Write response body to file path.");
        var failOnNonSuccessOpt = new Option<bool>("--fail-on-non-success", () => true, "Return non-zero on 4xx/5xx responses.");
        var verboseOpt = new Option<bool>("--verbose", "Enable verbose diagnostics logging.");
        var debugOpt = new Option<bool>("--debug", "Enable debug diagnostics.");
        var traceOpt = new Option<bool>("--trace", "Emit request/response trace diagnostics to stderr.");
        var retryNonIdempotentOpt = new Option<bool>("--retry-non-idempotent", "Allow retries for POST/PATCH methods.");
        var paginateOpt = new Option<bool>("--paginate", "Paginate GET requests using Jira values/startAt flow.");
        var explainOpt = new Option<bool>("--explain", "Show request endpoint and payload without executing.");
        var requestFileOpt = new Option<string?>("--request-file", "Write generated request payload and metadata to file.");
        var replayOpt = new Option<string?>("--replay", "Replay a request file generated by --request-file.");
        var yesOpt = new Option<bool>("--yes", "Confirm mutating operations.");
        var forceOpt = new Option<bool>("--force", "Force mutating operations.");

        command.AddArgument(methodArg);
        command.AddArgument(pathArg);
        command.AddOption(queryOpt);
        command.AddOption(headerOpt);
        command.AddOption(acceptOpt);
        command.AddOption(contentTypeOpt);
        command.AddOption(bodyOpt);
        command.AddOption(bodyFileOpt);
        command.AddOption(inOpt);
        command.AddOption(inputFormatOpt);
        command.AddOption(outOpt);
        command.AddOption(failOnNonSuccessOpt);
        command.AddOption(verboseOpt);
        command.AddOption(debugOpt);
        command.AddOption(traceOpt);
        command.AddOption(retryNonIdempotentOpt);
        command.AddOption(paginateOpt);
        command.AddOption(explainOpt);
        command.AddOption(requestFileOpt);
        command.AddOption(replayOpt);
        command.AddOption(yesOpt);
        command.AddOption(forceOpt);

        var symbols = new RequestCommandSymbols(
            methodArg,
            pathArg,
            queryOpt,
            headerOpt,
            acceptOpt,
            contentTypeOpt,
            bodyOpt,
            bodyFileOpt,
            inOpt,
            inputFormatOpt,
            outOpt,
            failOnNonSuccessOpt,
            verboseOpt,
            debugOpt,
            traceOpt,
            retryNonIdempotentOpt,
            paginateOpt,
            explainOpt,
            requestFileOpt,
            replayOpt,
            yesOpt,
            forceOpt);

        command.SetHandler(async context =>
        {
            await RequestCommandHandler.HandleAsync(services, context, symbols);
        });

        return command;
    }
}
